os: linux
dist: xenial
language: generic

jobs:
  include:
    - name: "Unit Tests using Python 3.6"
      env: TOX_ENV="py36-unit"
    - name: "Unit Tests using Python 3.7"
      env: TOX_ENV="py37-unit"
    - name: "Unit Tests using Python 3.8"
      env: TOX_ENV="py38-unit"

env:
  global:
    - DRAGONS_TEST="$HOME/dragons_tests/"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda config --add channels http://ssb.stsci.edu/astroconda
  - conda config --add channels http://astroconda.gemini.edu/public/noarch
  - conda config --set channel_priority false
  - conda config --set restore_free_channel true
  - conda env list
  - conda install --yes pip wheel
  - pip install "tox<=3.17.1" tox-conda

  # Useful for debugging any issues with conda
  - conda info -a

script:
  - tox -e $TOX_ENV -v
